resolver: lts-7.5

packages:
- '.'
- location: ../mockAPI
  extra-dep: false
- location:
    git: https://github.com/meditans/shaped 
    commit: 792e6b8adec1da3cbec982d026af3e5e39b25e40
  extra-dep: true

extra-deps: []

flags: {}

extra-package-dbs: []
