resolver: lts-7.13

packages:
- '.'
- location:
    git: https://github.com/meditans/shaped 
    commit: 0a750016b208bff6b7b9fe95e433a64c90db101a
  extra-dep: true

extra-deps: []
flags: {}
extra-package-dbs: []

