resolver: lts-7.13

packages:
- location: '.'
- location: ../mockAPI
  extra-dep: true
- location:
    git: https://github.com/reflex-frp/reflex
    commit: 91299fce0bb2caddfba35af6608df57dd31e3690
  extra-dep: true
- location:
    git: https://github.com/hamishmack/reflex-dom
    commit: 00c773be07693f38d981d6b99fac4a0571d45bd0
  extra-dep: true
- location:
    git: https://github.com/meditans/servant-reflex
    commit: 6953de90edc444f8f556b02639a2c64be6d1f6a9
  extra-dep: true
- location:
    git: https://github.com/ghcjs/jsaddle
    commit: 02f215aec0622300fd68f0200c813356ed7cd738
  subdirs:
  - jsaddle
  - jsaddle-warp
  extra-dep: true
- location:
    git: https://github.com/ghcjs/jsaddle-dom
    commit: 06351fe3562a2e6d096f6c862a9f5694ffd800d8
  extra-dep: true
- location:
    git: https://github.com/ghcjs/ghcjs-dom
    commit: 93165cae1c02e0d3859b4cd515e6bf0f1581e79b 
  extra-dep: true
  subdirs:
  - ghcjs-dom-jsffi
- location:
    git: https://github.com/meditans/shaped 
    commit: 0a750016b208bff6b7b9fe95e433a64c90db101a
  extra-dep: true

extra-deps:
- MemoTrie-0.6.7
- ghcjs-dom-0.7.0.3
- ghcjs-dom-jsaddle-0.7.0.3
- jsaddle-0.7.0.0
- jsaddle-dom-0.7.0.3
- jsaddle-warp-0.7.0.0
- newtype-generics-0.5
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1

flags: {}

extra-package-dbs: []
